
/* ================================================================ *
 *          Automatically generated by n-Blocks Studio 2.0          *
 *                                                                  *
 *                         www.n-blocks.net                         *
 * ================================================================ */
#include "nlib\nblocks.h"
#include "nlib\BSP\bsp.h"
// Custom nodes:
#include "nlib\nRF5xRadio\nrf5xradio.h"
#include "nlib\ArrayValue\arrayvalue.h"
#include "nlib\GPIN\gpin.h"
#include "nlib\ValueTrig\valuetrig.h"
#include "nlib\StringFormat\stringformat.h"
#include "nlib\L298\L298.h"
#include "nlib\Blink\blink.h"

// -*-*- List of node objects -*-*-
nBlock_nRF5xRadio        nb_nBlockNode0_nRF5xRadio   (RADIO_MODE_RX_ONLY, RADIO_RATE_2M, 2, 20, 0xC0, 0x55, 0x42, 0xBB, 0xC2);
nBlock_ArrayValue        nb_nBlockNode1_ArrayValue   (0, OUTPUT_TYPE_INT);
nBlock_GPIN              nb_nBlockNode2_GPIN         (P0_7, PullDown);
nBlock_ValueTrig         nb_nBlockNode3_ValueTrig    (0x32);
nBlock_StringFormat      nb_nBlockNode4_StringFormat ("%d");
nBlock_L298              nb_nBlockNode5_L298         (P0_20, P0_25, P0_24);
nBlock_GPIN              nb_nBlockNode6_GPIN         (P0_30, PullDown);
nBlock_ValueTrig         nb_nBlockNode7_ValueTrig    (0x30);
nBlock_Blink             nb_nBlockNode8_Blink        (50, P0_17);

// -*-*- List of connection objects -*-*-
nBlockConnection    n_conn0( &nb_nBlockNode6_GPIN,         1,    &nb_nBlockNode7_ValueTrig,    0);
nBlockConnection    n_conn1( &nb_nBlockNode4_StringFormat, 0,    &nb_nBlockNode5_L298,         0);
nBlockConnection    n_conn2( &nb_nBlockNode2_GPIN,         1,    &nb_nBlockNode3_ValueTrig,    0);
nBlockConnection    n_conn3( &nb_nBlockNode1_ArrayValue,   0,    &nb_nBlockNode4_StringFormat, 0);
nBlockConnection    n_conn4( &nb_nBlockNode3_ValueTrig,    0,    &nb_nBlockNode4_StringFormat, 0);
nBlockConnection    n_conn5( &nb_nBlockNode7_ValueTrig,    0,    &nb_nBlockNode4_StringFormat, 0);
nBlockConnection    n_conn6( &nb_nBlockNode0_nRF5xRadio,   0,    &nb_nBlockNode1_ArrayValue,   0);


// -*-*- Main function -*-*-
int main(void) {
    SetupWorkbench();
    while(1) {
        ProgressNodes();
        
        // Your custom code here!
    }
}
